version: 2.1
jobs:
  deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn global add netlify-cli
      - run: yarn build
      - run: yarn deploy
  # test:
  #   docker:
  #     - image: circleci/node:latest
  #   steps:
  #     - checkout
  #     - run: yarn install --frozen-lockfile
  #     - run: yarn test
workflows:
  build-app:
    jobs:
      # - test
      - deploy:
          requires:
            - test
