version: 2.1
jobs:
  deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: yarn global add netlify-cli
      - run: yarn build
      - run: netlify deploy --dir=build --prod
workflows:
  build-app:
    jobs:
      - deploy
